[project]
name = "demos"
version = "0.1.0"
description = "Short demo notebooks"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "cryptography>=46.0.3",
    "marimo>=0.17.7",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "ruff>=0.14.5",
]
